# Copied from https://github.com/numpy/numpy/blob/master/appveyor.yml
skip_tags: true
clone_depth: 1

os: Visual Studio 2015

build_script:
# If there's a newer build queued for the same PR, cancel this one
  - cl